/**
 * Fashion Store — 100 Product Seed
 * Usage:
 *   node seedProducts.js
 * OR import the array directly:
 *   const { products } = require('./seedProducts');
 *   await Product.insertMany(products);
 */

const mongoose = require('mongoose');
const Product = require('./src/server/models/Product'); // adjust path as needed

// ─── Unsplash image helpers ───────────────────────────────────────────────────
const img = (id) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;

// Curated, verified Unsplash photo IDs for fashion
const IMAGES = {
  // Men – Outerwear / Coats
  menCoat1:     img('1490481083-ee386e9a5f6d'),
  menCoat2:     img('1611241893603-3c359704311d'),
  menLeather:   img('1551028719-00167b16eac5'),
  menBlazer:    img('1469334031814-eed60825ab3a'),
  menParka:     img('1539185012-a37f50e5c1b8'),

  // Men – Ready-to-Wear / Casual
  menCasual1:   img('1503342217505-b0a15ec3261c'),
  menCasual2:   img('1526178613552-2b45c6c302f0'),
  menCasual3:   img('1596755094514-f87e34085b2c'),
  menTShirt1:   img('1583743814966-8936f5b7be1a'),
  menTShirt2:   img('1562886877-f0e13d18caad'),
  menHoodie:    img('1591047139829-d91aecb6caea'),
  menSuit1:     img('1617137968427-85924c800a22'),
  menSuit2:     img('1507679799987-c73779587ccf'),
  menTrousers:  img('1568252542512-9fe8fe9f6fe1'),
  menDenim:     img('1542219222-7b2c2e0d0613'),

  // Women – Outerwear / Coats
  womenCoat1:   img('1539109136881-3be0616acf4b'),
  womenCoat2:   img('1516762844-6a6aa9c5a45e'),
  womenLeather: img('1480522838-f2aa85ebe66f'),
  womenBlazer:  img('1551489186-cf8726f514f8'),

  // Women – Ready-to-Wear / Casual
  womenCasual1: img('1515886657613-9f3515b0c78f'),
  womenCasual2: img('1517841905240-472988babdf9'),
  womenCasual3: img('1584370848010-d7fe6bc767ec'),
  womenDress1:  img('1434389677669-e08b4cac3105'),
  womenDress2:  img('1441984904996-e0b6ba687e04'),
  womenBlouse:  img('1614093302611-8efc673e8a7e'),
  womenSkirt:   img('1611911813383-3b8bb99a9e0a'),

  // Eveningwear
  eveningW1:    img('1566174053879-31528523f8ae'),
  eveningW2:    img('1622519407650-3df9d62496f7'),
  eveningM1:    img('1505022610485-0249ba5b3967'),

  // Knitwear
  knit1:        img('1576566588405-09af1685f038'),
  knit2:        img('1604004555489-723a93d6ce74'),
  knit3:        img('1594938298603-a3554ef9b09e'),
  knit4:        img('1620799139-86c8b47c9e52'),

  // Athleisure
  athleisure1:  img('1523381210434-271e8be1f52b'),
  athleisure2:  img('1574226516797-87609b0406bc'),
  athleisure3:  img('1571019613454-1cb2f99b2d8b'),
  athleisure4:  img('1517344368193-41552b6ad3f5'),

  // Footwear
  sneaker1:     img('1542291026-7eec264c27ff'),
  sneaker2:     img('1560769629-975ec94e6a86'),
  sneaker3:     img('1549298916-b41d501d3772'),
  boots1:       img('1608256246200-ca4e7f79bfef'),
  boots2:       img('1520639888713-7851133b1ed0'),
  loafer1:      img('1533867522750-0e0e21e1cc28'),
  heels1:       img('1543163521-1bf539c55dd2'),
  heels2:       img('1596703263926-eb0762ee17e4'),

  // Accessories
  bag1:         img('1548036161-0c46e5c8c43c'),
  bag2:         img('1584917865442-de89df76afd3'),
  bag3:         img('1590874103328-eac38a683ce7'),
  scarf1:       img('1520903074185-8ebdfbe0a3e0'),
  belt1:        img('1624378439575-d8705ad7ae80'),
  watch1:       img('1523275335684-37898b6baf30'),
  sunglasses1:  img('1511499767150-a7a1371514b1'),
  hat1:         img('1521369909029-2afed882baee'),
};

// ─── Seed Data ────────────────────────────────────────────────────────────────
const products = [
  // ══════════════════════════════════════════════════════
  // OUTERWEAR (12)
  // ══════════════════════════════════════════════════════
  {
    name: 'Heritage Double-Breasted Wool Overcoat',
    price: 42000,
    description: 'A timeless double-breasted overcoat crafted from premium Italian wool. Features notched lapels, horn buttons, and a tailored silhouette that transitions seamlessly from boardroom to evening.',
    image: IMAGES.menCoat1,
    category: 'Outerwear',
    gender: 'Men',
    season: 'Winter',
    stock: 24,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Camel', 'Navy'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 112,
    reviews: [],
  },
  {
    name: 'Arctic Shield Insulated Parka',
    price: 28500,
    description: 'Engineered for extreme cold, this parka features 700-fill goose down insulation, a fur-trim hood, and waterproof shell. Functional yet sophisticated.',
    image: IMAGES.menParka,
    category: 'Outerwear',
    gender: 'Men',
    season: 'Winter',
    stock: 18,
    trending: false,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Olive', 'Navy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 15,
    rating: 4.6,
    numReviews: 87,
    reviews: [],
  },
  {
    name: 'Smooth Grain Italian Leather Biker Jacket',
    price: 55000,
    description: 'A contemporary biker jacket rendered in full-grain Italian leather. Asymmetric zip, quilted shoulder panels, and a slightly cropped cut give it an edge-meets-luxury appeal.',
    image: IMAGES.menLeather,
    category: 'Outerwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 15,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown'],
    brand: 'Atelier X',
    material: 'Leather',
    fit: 'Slim Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 64,
    reviews: [],
  },
  {
    name: 'Structured Single-Button Blazer',
    price: 18500,
    description: 'Sharp, single-button blazer with structured shoulders and a clean front. Crafted in a linen-wool blend, ideal for layering through transitional seasons.',
    image: IMAGES.menBlazer,
    category: 'Outerwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 30,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Charcoal', 'Beige'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Tailored',
    occasion: 'Work',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 93,
    reviews: [],
  },
  {
    name: 'Belted Cashmere Wrap Coat',
    price: 68000,
    description: 'An effortlessly chic wrap coat in pure cashmere. The self-tie belt accentuates the waist while the wide lapels add a dramatic, fashion-forward quality.',
    image: IMAGES.womenCoat1,
    category: 'Outerwear',
    gender: 'Women',
    season: 'Winter',
    stock: 12,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Camel', 'Ivory', 'Black'],
    brand: 'Heritage',
    material: 'Cashmere',
    fit: 'Relaxed Fit',
    occasion: 'Formal',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 76,
    reviews: [],
  },
  {
    name: 'Oversized Checked Wool Coat',
    price: 34000,
    description: 'A bold, oversized wool coat in a heritage check pattern. Dropped shoulders and a straight cut create a modern, statement silhouette.',
    image: IMAGES.womenCoat2,
    category: 'Outerwear',
    gender: 'Women',
    season: 'Winter',
    stock: 20,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Black'],
    brand: 'Atelier X',
    material: 'Wool',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: true,
    discountPercent: 10,
    rating: 4.7,
    numReviews: 58,
    reviews: [],
  },
  {
    name: 'Cropped Moto Leather Jacket — Women',
    price: 48000,
    description: 'A cropped moto jacket in buttery-soft lambskin leather. Its slightly fitted shape and asymmetric zip make it the ultimate elevated-casual topper.',
    image: IMAGES.womenLeather,
    category: 'Outerwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 14,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Tan'],
    brand: 'Atelier X',
    material: 'Leather',
    fit: 'Slim Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 45,
    reviews: [],
  },
  {
    name: 'Longline Blazer Coat — Women',
    price: 22000,
    description: 'A longline blazer-coat hybrid that blurs the boundary between suiting and outerwear. Clean lapels, patch pockets, and a barely-there waist seam.',
    image: IMAGES.womenBlazer,
    category: 'Outerwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 22,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Charcoal', 'Burgundy'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Tailored',
    occasion: 'Work',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 61,
    reviews: [],
  },
  {
    name: 'Unisex Technical Shell Jacket',
    price: 19500,
    description: 'A weather-resistant shell jacket built for city commutes and light trails alike. Recycled nylon shell, packable hood, and minimal branding.',
    image: IMAGES.athleisure3,
    category: 'Outerwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 40,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Olive', 'Navy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.4,
    numReviews: 134,
    reviews: [],
  },
  {
    name: 'Quilted Down Vest — Unisex',
    price: 12500,
    description: 'A lightweight quilted vest with 550-fill recycled down insulation. Sleeveless design layers easily over shirts or under heavier coats.',
    image: IMAGES.athleisure4,
    category: 'Outerwear',
    gender: 'Unisex',
    season: 'Winter',
    stock: 35,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Burgundy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 20,
    rating: 4.3,
    numReviews: 99,
    reviews: [],
  },
  {
    name: 'Tailored Pinstripe Suit Jacket',
    price: 36000,
    description: 'A sharp pinstripe suit jacket with a half-canvas construction. Peak lapels, double-button closure, and a clean back vent define its power dressing credentials.',
    image: IMAGES.menSuit1,
    category: 'Outerwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 16,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Charcoal'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 52,
    reviews: [],
  },
  {
    name: 'Evening Dinner Jacket',
    price: 44000,
    description: 'A midnight-blue evening jacket with satin lapels and a single-button closure. Crafted in super 120s wool for a lustrous drape worthy of black-tie events.',
    image: IMAGES.eveningM1,
    category: 'Outerwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 10,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Black'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 41,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // READY-TO-WEAR (20)
  // ══════════════════════════════════════════════════════
  {
    name: 'Supima Cotton Crew-Neck T-Shirt',
    price: 3200,
    description: 'Made from 190gsm Supima cotton, this essential crew-neck tee offers a weightier, luxury hand-feel. Pre-washed for softness, minimal shrinkage.',
    image: IMAGES.menTShirt1,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'Summer',
    stock: 120,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Grey', 'Navy'],
    brand: 'Minimalist',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 310,
    reviews: [],
  },
  {
    name: 'Slim-Fit Oxford Button-Down Shirt',
    price: 5800,
    description: 'A wardrobe cornerstone: crisp Oxford-weave button-down in slim fit. Tucked or untucked, it transitions effortlessly from desk to dinner.',
    image: IMAGES.menCasual1,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'All-Season',
    stock: 80,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Blue', 'Pink'],
    brand: 'Heritage',
    material: 'Cotton',
    fit: 'Slim Fit',
    occasion: 'Work',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 185,
    reviews: [],
  },
  {
    name: 'Premium Raw Selvedge Denim Jeans',
    price: 12000,
    description: 'Japanese raw selvedge denim in a slim tapered cut. 14.5oz fabric, copper rivets, and clean front pockets. Will patina beautifully over time.',
    image: IMAGES.menDenim,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'All-Season',
    stock: 45,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Indigo', 'Black'],
    brand: 'Atelier X',
    material: 'Cotton',
    fit: 'Slim Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 98,
    reviews: [],
  },
  {
    name: 'Relaxed Linen Wide-Leg Trousers',
    price: 7500,
    description: 'Breezy wide-leg trousers in stone-washed linen. An elasticated waistband, side pockets, and a relaxed fall make these the ultimate warm-weather essential.',
    image: IMAGES.menTrousers,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'Summer',
    stock: 55,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Beige', 'White', 'Olive'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: true,
    discountPercent: 10,
    rating: 4.4,
    numReviews: 72,
    reviews: [],
  },
  {
    name: 'Organic Cotton Pullover Hoodie',
    price: 8500,
    description: 'A heavyweight 380gsm organic cotton hoodie with a kangaroo pocket, ribbed cuffs, and a slightly boxy fit. Garment-dyed for a rich, lived-in tone.',
    image: IMAGES.menHoodie,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'All-Season',
    stock: 90,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey', 'Brown', 'Navy'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 247,
    reviews: [],
  },
  {
    name: 'Merino Wool Polo Shirt',
    price: 9200,
    description: 'A luxury polo in 18.5-micron merino wool. Temperature-regulating, odor-resistant, and wrinkle-resistant — designed for all-day comfort.',
    image: IMAGES.menCasual2,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'All-Season',
    stock: 60,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Burgundy', 'Olive'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 119,
    reviews: [],
  },
  {
    name: 'Tailored Suit Trousers',
    price: 14500,
    description: 'Precision-cut trousers in a super 110s wool blend. Mid-rise, single pleat, and clean side pockets. Pairs perfectly with the matching Heritage blazer.',
    image: IMAGES.menSuit2,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'All-Season',
    stock: 35,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Navy', 'Black'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 63,
    reviews: [],
  },
  {
    name: 'Flowy Viscose Midi Dress',
    price: 8800,
    description: 'A V-neck midi dress in fluid viscose. Smocked bodice, fluted hem, and adjustable spaghetti straps. Prints shift seasonally — check current stock for available colorways.',
    image: IMAGES.womenDress1,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'Summer',
    stock: 65,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Floral-Print', 'Black', 'White'],
    brand: 'Minimalist',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 154,
    reviews: [],
  },
  {
    name: 'Cotton Linen Wide-Leg Culottes',
    price: 6200,
    description: 'Easy-wearing cotton-linen culottes with a wide-leg crop and a side-zip closure. Press creases lend a tailored neatness to an otherwise relaxed cut.',
    image: IMAGES.womenCasual1,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'Summer',
    stock: 48,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Beige', 'Olive'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: true,
    discountPercent: 15,
    rating: 4.5,
    numReviews: 88,
    reviews: [],
  },
  {
    name: 'Stretch-Crepe Blazer Dress',
    price: 14000,
    description: 'A sculptural blazer dress in stretch crepe. Single-button front, notched lapels, and a barely-there mini length that commands a room.',
    image: IMAGES.womenBlouse,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'All-Season',
    stock: 28,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Burgundy'],
    brand: 'Atelier X',
    material: 'Technical',
    fit: 'Tailored',
    occasion: 'Work',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 77,
    reviews: [],
  },
  {
    name: 'Smocked Cotton Maxi Dress',
    price: 9500,
    description: 'A romantic maxi dress in 100% organic cotton. Fully elasticated smocked bodice, puff sleeves, and a tiered skirt with a gentle ruffle hem.',
    image: IMAGES.womenDress2,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'Summer',
    stock: 52,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Sage', 'Dusty-Rose'],
    brand: 'Fashion Hub',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic', 'Hand-crafted'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 143,
    reviews: [],
  },
  {
    name: 'Satin Bias-Cut Slip Skirt',
    price: 7200,
    description: 'Effortlessly elegant bias-cut skirt in liquid satin. Falls to the mid-calf with a barely-there seam and delicate side split.',
    image: IMAGES.womenSkirt,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'All-Season',
    stock: 38,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Champagne'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 95,
    reviews: [],
  },
  {
    name: 'Oversized Graphic Tee — Unisex',
    price: 3800,
    description: 'A boxy, heavyweight 220gsm tee with a hand-printed graphic motif. Dropped shoulders and a longer hem give it a relaxed, contemporary profile.',
    image: IMAGES.menCasual3,
    category: 'Ready-to-Wear',
    gender: 'Unisex',
    season: 'Summer',
    stock: 150,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Grey'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.4,
    numReviews: 320,
    reviews: [],
  },
  {
    name: 'Linen Relaxed Shirt — Unisex',
    price: 5500,
    description: 'A gender-neutral relaxed linen shirt with a mandarin collar and mother-of-pearl buttons. Washes beautifully and only improves with age.',
    image: IMAGES.womenCasual2,
    category: 'Ready-to-Wear',
    gender: 'Unisex',
    season: 'Summer',
    stock: 70,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Ecru', 'Pale-Blue'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Organic', 'Vegan'],
    isSale: true,
    discountPercent: 10,
    rating: 4.5,
    numReviews: 108,
    reviews: [],
  },
  {
    name: 'Crepe High-Waist Tapered Trousers — Women',
    price: 8900,
    description: 'High-rise tapered trousers in stretch crepe. Invisible zip closure, front welt pockets, and a clean front crease for a polished, versatile look.',
    image: IMAGES.womenCasual3,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'All-Season',
    stock: 42,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Camel'],
    brand: 'Fashion Hub',
    material: 'Technical',
    fit: 'Tailored',
    occasion: 'Work',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 79,
    reviews: [],
  },
  {
    name: 'Slim Merino Turtleneck',
    price: 7800,
    description: 'A sleek, slim turtleneck in extra-fine 17.5-micron merino. Machine washable and lightweight enough to layer under a blazer or coat without bulk.',
    image: IMAGES.menTShirt2,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'Winter',
    stock: 55,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Ivory', 'Grey', 'Navy'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Slim Fit',
    occasion: 'Work',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 131,
    reviews: [],
  },
  {
    name: 'Silk Charmeuse Blouse',
    price: 13500,
    description: 'A fluid silk charmeuse blouse with a pussy-bow neckline and a relaxed, untucked drape. Luxurious sheen that elevates any bottom.',
    image: IMAGES.womenBlouse,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'All-Season',
    stock: 30,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Blush', 'Black'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Relaxed Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 67,
    reviews: [],
  },
  {
    name: 'French Terry Sweatpants',
    price: 6500,
    description: 'Soft-brushed French terry sweatpants with a mid-rise drawstring waist, tapered leg, and ribbed cuffs. Elevated loungewear with a clean, minimal aesthetic.',
    image: IMAGES.athleisure2,
    category: 'Ready-to-Wear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 85,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Black', 'Cream'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Relaxed Fit',
    occasion: 'Lounge',
    sustainability: ['Organic'],
    isSale: true,
    discountPercent: 10,
    rating: 4.4,
    numReviews: 192,
    reviews: [],
  },
  {
    name: 'Ribbed Cotton-Modal Tank — Women',
    price: 2800,
    description: 'A fine-ribbed tank in a cotton-modal blend. Scoop neck, wide straps, and a fitted cut. The foundational layer for any capsule wardrobe.',
    image: IMAGES.womenCasual2,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'Summer',
    stock: 140,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Beige', 'Olive'],
    brand: 'Minimalist',
    material: 'Cotton',
    fit: 'Slim Fit',
    occasion: 'Casual',
    sustainability: ['Organic', 'Vegan'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 268,
    reviews: [],
  },
  {
    name: 'Cargo Utility Trousers — Unisex',
    price: 9200,
    description: 'A fashion-forward take on the utility trouser. Six functional cargo pockets, adjustable ankle tabs, and a relaxed fit in durable ripstop cotton.',
    image: IMAGES.menCasual2,
    category: 'Ready-to-Wear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 50,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Olive', 'Black', 'Tan'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 115,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // EVENINGWEAR (8)
  // ══════════════════════════════════════════════════════
  {
    name: 'Silk Organza Ballgown',
    price: 120000,
    description: 'A sweeping ballgown in triple-layered silk organza. The corseted bodice, hand-applied floral embellishments, and cathedral-length skirt make this a true heirloom piece.',
    image: IMAGES.eveningW1,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 4,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Blush', 'Midnight'],
    brand: 'Heritage',
    material: 'Silk',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: ['Hand-crafted'],
    isSale: false,
    discountPercent: 0,
    rating: 5.0,
    numReviews: 22,
    reviews: [],
  },
  {
    name: 'Sequined Column Gown',
    price: 85000,
    description: 'A sleek column gown entirely encrusted in micro-sequins. The minimal silhouette — narrow shoulders, bateau neck, and floor-length hem — lets the shimmer speak.',
    image: IMAGES.eveningW2,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 6,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Gold', 'Silver'],
    brand: 'Atelier X',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 34,
    reviews: [],
  },
  {
    name: 'Velvet Off-Shoulder Cocktail Dress',
    price: 48000,
    description: 'A midnight-blue velvet cocktail dress with an off-shoulder neckline and a fluted knee-length hem. Lined in silk charmeuse for a sumptuous feel against the skin.',
    image: IMAGES.womenDress2,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'Winter',
    stock: 10,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Midnight', 'Emerald', 'Burgundy'],
    brand: 'Heritage',
    material: 'Silk',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 48,
    reviews: [],
  },
  {
    name: 'Silk Crepe Wrap Gown',
    price: 62000,
    description: 'A fluid wrap gown in heavy silk crepe. Deep V-neckline, cascading skirt, and a self-tie waist — endlessly versatile between cocktail and black-tie occasions.',
    image: IMAGES.eveningW1,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 8,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Black', 'Champagne'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: true,
    discountPercent: 10,
    rating: 4.9,
    numReviews: 29,
    reviews: [],
  },
  {
    name: 'Beaded Fringe Mini Dress',
    price: 72000,
    description: 'Inspired by 1920s opulence, this mini dress features thousands of hand-sewn glass beads on a sheer mesh base. Fringe hem that moves with every step.',
    image: IMAGES.eveningW2,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 5,
    trending: true,
    sizes: ['XS', 'S', 'M'],
    colors: ['Gold', 'Silver', 'Black'],
    brand: 'Heritage',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: ['Hand-crafted'],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 17,
    reviews: [],
  },
  {
    name: 'Black Tie Tuxedo Set',
    price: 95000,
    description: 'A complete black-tie tuxedo comprising a satin-lapel dinner jacket, matching trousers with a single satin side stripe, and a pocket square. Ready-to-wear perfection.',
    image: IMAGES.eveningM1,
    category: 'Eveningwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 8,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Midnight-Blue'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Tailored',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 38,
    reviews: [],
  },
  {
    name: 'Embroidered Silk Kurta — Unisex',
    price: 28000,
    description: 'Handcrafted silk kurta with intricate zardozi embroidery at the neckline and cuffs. A celebration of South Asian artisanship in a modern, relaxed silhouette.',
    image: IMAGES.menSuit1,
    category: 'Eveningwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 15,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Gold', 'Deep-Teal'],
    brand: 'Heritage',
    material: 'Silk',
    fit: 'Relaxed Fit',
    occasion: 'Formal',
    sustainability: ['Hand-crafted', 'Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 55,
    reviews: [],
  },
  {
    name: 'Feather-Trim Cape Blouse',
    price: 35000,
    description: 'A sculptural blouse with a feather-trimmed Cape overlay. Silk shell with a concealed zip back. Dramatic and feminine — an instant talking point.',
    image: IMAGES.womenSkirt,
    category: 'Eveningwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 7,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Ivory', 'Blush'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 23,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // KNITWEAR (10)
  // ══════════════════════════════════════════════════════
  {
    name: 'Pure Cashmere Crewneck Sweater',
    price: 32000,
    description: 'Grade-A Mongolian cashmere in a classic crewneck. Two-ply construction for warmth without weight. The definitive cold-weather luxury.',
    image: IMAGES.knit3,
    category: 'Knitwear',
    gender: 'Men',
    season: 'Winter',
    stock: 35,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Grey', 'Navy', 'Black'],
    brand: 'Heritage',
    material: 'Cashmere',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 142,
    reviews: [],
  },
  {
    name: 'Chunky Rib-Knit Turtleneck',
    price: 18500,
    description: 'An oversized chunky-knit turtleneck in a merino-wool blend. Wide rib construction, voluminous silhouette, and drop shoulders for a cocooning, modern feel.',
    image: IMAGES.knit1,
    category: 'Knitwear',
    gender: 'Women',
    season: 'Winter',
    stock: 28,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ecru', 'Caramel', 'Grey'],
    brand: 'Minimalist',
    material: 'Wool',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 97,
    reviews: [],
  },
  {
    name: 'Intarsia Argyle V-Neck Sweater',
    price: 14000,
    description: 'A heritage argyle intarsia V-neck in a merino-cashmere blend. Classic diamond motif in a refined, updated palette. Smart casual at its finest.',
    image: IMAGES.knit3,
    category: 'Knitwear',
    gender: 'Men',
    season: 'Winter',
    stock: 40,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Burgundy', 'Forest'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: true,
    discountPercent: 15,
    rating: 4.5,
    numReviews: 76,
    reviews: [],
  },
  {
    name: 'Open-Knit Crochet Cover-Up',
    price: 11000,
    description: 'A hand-crocheted open-knit cover-up in 100% cotton. Perfect layered over a swimsuit or paired with high-waisted trousers for a relaxed summer look.',
    image: IMAGES.womenCasual1,
    category: 'Knitwear',
    gender: 'Women',
    season: 'Summer',
    stock: 22,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Ecru', 'Terracotta'],
    brand: 'Fashion Hub',
    material: 'Cotton',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Hand-crafted', 'Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 58,
    reviews: [],
  },
  {
    name: 'Cashmere-Blend Cardigan',
    price: 22000,
    description: 'A timeless cardigan in a cashmere-merino blend. Single-breasted horn-button fastening, ribbed edges, and two patch pockets. Endlessly versatile.',
    image: IMAGES.knit2,
    category: 'Knitwear',
    gender: 'Unisex',
    season: 'Winter',
    stock: 45,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Grey', 'Navy', 'Brown'],
    brand: 'Heritage',
    material: 'Cashmere',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 113,
    reviews: [],
  },
  {
    name: 'Sheer Mohair Fluffy Sweater',
    price: 16500,
    description: 'A playfully textured mohair sweater with a delicate halo finish. Oversized drop-shoulder silhouette in a lightly brushed yarn that catches the light.',
    image: IMAGES.knit4,
    category: 'Knitwear',
    gender: 'Women',
    season: 'Winter',
    stock: 18,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blush', 'Lavender', 'Ivory'],
    brand: 'Atelier X',
    material: 'Wool',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 84,
    reviews: [],
  },
  {
    name: 'Cotton Waffle-Knit Henley',
    price: 6800,
    description: 'A casual waffle-knit Henley in organic cotton. Three-button placket, long sleeves, and a slightly relaxed fit. Perfect for layering or wearing alone.',
    image: IMAGES.menCasual1,
    category: 'Knitwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 65,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Ecru', 'Grey', 'Navy', 'Olive'],
    brand: 'Minimalist',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: true,
    discountPercent: 10,
    rating: 4.4,
    numReviews: 102,
    reviews: [],
  },
  {
    name: 'Knitted Crop Co-ord Set',
    price: 19500,
    description: 'A matching knitted crop top and mini skirt in a fine-gauge rib. The co-ord can be styled together or as separates. Sold as a set.',
    image: IMAGES.knit1,
    category: 'Knitwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 25,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ecru', 'Black', 'Chocolate'],
    brand: 'Fashion Hub',
    material: 'Cotton',
    fit: 'Slim Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 67,
    reviews: [],
  },
  {
    name: 'Oversized Fisherman Knit Sweater',
    price: 15500,
    description: 'A rugged fisherman-knit sweater in 100% organic Irish wool. Cable-knit panels, ribbed collar, and an oversized unisex fit built to last decades.',
    image: IMAGES.knit2,
    category: 'Knitwear',
    gender: 'Unisex',
    season: 'Winter',
    stock: 30,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Ecru', 'Grey', 'Navy'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Oversized',
    occasion: 'Casual',
    sustainability: ['Organic', 'Hand-crafted'],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 121,
    reviews: [],
  },
  {
    name: 'Lightweight Merino Longline Cardigan',
    price: 20000,
    description: 'A duster-length cardigan in lightweight merino wool. Open-front, side-slit hem, and a relaxed, graceful drape. The elevated alternative to a coat in mild weather.',
    image: IMAGES.knit4,
    category: 'Knitwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 20,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Camel', 'Grey', 'Black'],
    brand: 'Minimalist',
    material: 'Wool',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: true,
    discountPercent: 20,
    rating: 4.6,
    numReviews: 89,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // ATHLEISURE (12)
  // ══════════════════════════════════════════════════════
  {
    name: 'Performance Compression Leggings',
    price: 8500,
    description: 'Four-way stretch compression leggings in recycled nylon. High-waist design, hidden waistband pocket, and flatlock seams for zero-chafe comfort during high-intensity workouts.',
    image: IMAGES.athleisure2,
    category: 'Athleisure',
    gender: 'Women',
    season: 'All-Season',
    stock: 80,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Cobalt'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 215,
    reviews: [],
  },
  {
    name: 'Contour Seamless Sports Bra',
    price: 5500,
    description: 'A medium-support seamless sports bra with contour cups and adjustable straps. Ultra-soft fabric moves with you and wicks moisture efficiently.',
    image: IMAGES.athleisure1,
    category: 'Athleisure',
    gender: 'Women',
    season: 'All-Season',
    stock: 90,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Blush', 'Sage'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 10,
    rating: 4.5,
    numReviews: 178,
    reviews: [],
  },
  {
    name: 'Tapered Training Joggers — Men',
    price: 7200,
    description: 'Tapered training joggers in a moisture-wicking poly-spandex blend. Zip pockets, elasticated waist, and a performance-ready fit that works equally well at the gym or on the street.',
    image: IMAGES.athleisure3,
    category: 'Athleisure',
    gender: 'Men',
    season: 'All-Season',
    stock: 70,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey', 'Navy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 143,
    reviews: [],
  },
  {
    name: 'Yoga Flow Studio Pants',
    price: 9500,
    description: 'Ultra-soft yoga pants in a butter-smooth nylon-spandex blend. Wide waistband, flared leg, and a high-rise cut that stays in place through the most dynamic flows.',
    image: IMAGES.athleisure4,
    category: 'Athleisure',
    gender: 'Women',
    season: 'All-Season',
    stock: 60,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Sage', 'Dusty-Rose', 'Black'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 196,
    reviews: [],
  },
  {
    name: 'Lightweight Running Jacket',
    price: 11000,
    description: 'A packable running jacket in wind-resistant ripstop. Reflective details, ventilated underarms, and a race-back construction for unrestricted movement.',
    image: IMAGES.athleisure3,
    category: 'Athleisure',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 40,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Electric-Blue', 'Orange'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 15,
    rating: 4.4,
    numReviews: 88,
    reviews: [],
  },
  {
    name: 'Performance Quarter-Zip Pullover',
    price: 8000,
    description: 'A technical quarter-zip pullover in moisture-wicking mid-layer fleece. Raglan sleeves, thumbholes, and a slim-fit cut that layers under a shell jacket.',
    image: IMAGES.athleisure1,
    category: 'Athleisure',
    gender: 'Men',
    season: 'Winter',
    stock: 45,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Grey'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 107,
    reviews: [],
  },
  {
    name: 'Tencel Lounge Set — Women',
    price: 12500,
    description: 'A matching lounge top and wide-leg pant in TENCEL™ Lyocell. Impossibly soft, temperature-regulating, and refined enough for off-duty outings. Sold as a set.',
    image: IMAGES.athleisure2,
    category: 'Athleisure',
    gender: 'Women',
    season: 'All-Season',
    stock: 35,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Sage', 'Ecru', 'Dusty-Rose'],
    brand: 'Fashion Hub',
    material: 'Technical',
    fit: 'Relaxed Fit',
    occasion: 'Lounge',
    sustainability: ['Vegan', 'Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 122,
    reviews: [],
  },
  {
    name: 'Pro-Fit Gym Shorts — Men',
    price: 4500,
    description: '5-inch inseam gym shorts with a split-hem, internal liner, and zippered back pocket. Lightweight, quick-dry fabric ideal for training, running, or casual wear.',
    image: IMAGES.athleisure4,
    category: 'Athleisure',
    gender: 'Men',
    season: 'Summer',
    stock: 100,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Grey', 'Olive'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.4,
    numReviews: 234,
    reviews: [],
  },
  {
    name: 'Open-Back Strappy Sports Top',
    price: 6200,
    description: 'A multi-strap open-back top in a double-layer support mesh. Sweetheart neckline, built-in bra cups, and a crop-length hem. Eye-catching form meets serious function.',
    image: IMAGES.athleisure1,
    category: 'Athleisure',
    gender: 'Women',
    season: 'Summer',
    stock: 55,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'White', 'Cobalt'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 10,
    rating: 4.5,
    numReviews: 161,
    reviews: [],
  },
  {
    name: 'Biker Shorts — Unisex',
    price: 5200,
    description: 'High-waist 8-inch inseam biker shorts in a compression-lite recycled nylon blend. Clean, minimal design that transitions from the studio to the street.',
    image: IMAGES.athleisure2,
    category: 'Athleisure',
    gender: 'Unisex',
    season: 'Summer',
    stock: 85,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Sage', 'Navy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 189,
    reviews: [],
  },
  {
    name: 'Studio Zip-Up Track Jacket',
    price: 9800,
    description: 'A clean-lined zip-up track jacket in brushed-back jersey. Ribbed collar, cuffs and hem, side pockets, and a relaxed athletic cut.',
    image: IMAGES.athleisure3,
    category: 'Athleisure',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 50,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey', 'Burgundy'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 148,
    reviews: [],
  },
  {
    name: 'Training Hoodie with Kangaroo Pocket',
    price: 8900,
    description: 'A training hoodie in moisture-wicking, anti-odor fabric. Kangaroo pocket, adjustable drawcord hood, and a slightly cropped hem designed to move with your body.',
    image: IMAGES.menHoodie,
    category: 'Athleisure',
    gender: 'Men',
    season: 'All-Season',
    stock: 60,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Olive'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 10,
    rating: 4.5,
    numReviews: 174,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // FOOTWEAR (15)
  // ══════════════════════════════════════════════════════
  {
    name: 'Clean Leather Low-Top Sneaker',
    price: 14500,
    description: 'A minimalist full-grain leather sneaker with a cupsole construction and a discreet logo tab. Inspired by classic tennis shoes, elevated for modern wardrobes.',
    image: IMAGES.sneaker1,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 60,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Cream'],
    brand: 'Minimalist',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 243,
    reviews: [],
  },
  {
    name: 'Chunky Platform Sneaker',
    price: 18000,
    description: 'An exaggerated chunky sole platform sneaker in premium leather with suede overlays. A statement shoe that grounds any outfit.',
    image: IMAGES.sneaker2,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 35,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Multicolour'],
    brand: 'Urban Luxe',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 132,
    reviews: [],
  },
  {
    name: 'High-Performance Running Shoe',
    price: 16500,
    description: 'A responsive running shoe with carbon-fibre plate, energy-return foam midsole, and a breathable engineered mesh upper. Built for personal bests.',
    image: IMAGES.sneaker3,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 50,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Neon-Green'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: true,
    discountPercent: 10,
    rating: 4.7,
    numReviews: 189,
    reviews: [],
  },
  {
    name: 'Knee-High Leather Riding Boots',
    price: 42000,
    description: 'Classic knee-high riding boots in smooth Italian calf leather. Block heel, pull-on tabs, and a full-length side zip. A timeless wardrobe investment.',
    image: IMAGES.boots1,
    category: 'Footwear',
    gender: 'Women',
    season: 'Winter',
    stock: 18,
    trending: true,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Tan'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 94,
    reviews: [],
  },
  {
    name: 'Chelsea Ankle Boot — Men',
    price: 22000,
    description: 'A streamlined Chelsea boot in water-resistant calf leather. Elastic side gussets, pull-tab heel, and a lightweight Goodyear-welted sole.',
    image: IMAGES.boots2,
    category: 'Footwear',
    gender: 'Men',
    season: 'Winter',
    stock: 28,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 118,
    reviews: [],
  },
  {
    name: 'Leather Penny Loafer',
    price: 18500,
    description: 'A classic penny loafer in hand-burnished calfskin. Leather outsole with a rubber heel cap for comfort. A perennial wardrobe cornerstone.',
    image: IMAGES.loafer1,
    category: 'Footwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 32,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Tan', 'Black', 'Brown'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Work',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 87,
    reviews: [],
  },
  {
    name: 'Strappy Block-Heel Sandals',
    price: 16000,
    description: 'Square-toe block-heel sandals with criss-cross straps and a buckle ankle fastening. Padded insole, 7 cm heel. Day-to-evening versatility.',
    image: IMAGES.heels1,
    category: 'Footwear',
    gender: 'Women',
    season: 'Summer',
    stock: 25,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Beige', 'Black', 'White'],
    brand: 'Fashion Hub',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 111,
    reviews: [],
  },
  {
    name: 'Pointed-Toe Stiletto Pump',
    price: 24000,
    description: 'A sleek pointed-toe pump on a 10 cm stiletto heel in patent leather. The quintessential power shoe for meetings, dinners, and everything in between.',
    image: IMAGES.heels2,
    category: 'Footwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 20,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Nude', 'Red'],
    brand: 'Atelier X',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 76,
    reviews: [],
  },
  {
    name: 'Suede Lug-Sole Derby',
    price: 19500,
    description: 'A chunky lug-sole derby in premium suede. Brogue detailing along the toe cap and split saddle. Pairs as naturally with tailoring as it does with denim.',
    image: IMAGES.loafer1,
    category: 'Footwear',
    gender: 'Men',
    season: 'All-Season',
    stock: 22,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Brown', 'Tan', 'Charcoal'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: true,
    discountPercent: 20,
    rating: 4.6,
    numReviews: 68,
    reviews: [],
  },
  {
    name: 'Trail-Ready Hiking Boot',
    price: 15000,
    description: 'A waterproof hiking boot with a full-grain leather upper, cushioned EVA midsole, and aggressive rubber outsole. Ankle support and all-terrain traction for any adventure.',
    image: IMAGES.boots2,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'Winter',
    stock: 30,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Brown', 'Black'],
    brand: 'Zenith',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Active',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 143,
    reviews: [],
  },
  {
    name: 'Leather Ballet Flat',
    price: 10500,
    description: 'Buttery-soft nappa leather ballet flats with a square toe and a delicate grosgrain bow. Lined in genuine leather for all-day comfort.',
    image: IMAGES.heels1,
    category: 'Footwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 40,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Beige', 'Burgundy'],
    brand: 'Minimalist',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Work',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 165,
    reviews: [],
  },
  {
    name: 'Slip-On Canvas Espadrille',
    price: 6500,
    description: 'A relaxed slip-on espadrille with a canvas upper and a jute-rope platform. Hand-stitched in Spain. The definitive summer shoe.',
    image: IMAGES.sneaker1,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'Summer',
    stock: 55,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Navy', 'Stripe'],
    brand: 'Fashion Hub',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Hand-crafted', 'Vegan'],
    isSale: true,
    discountPercent: 10,
    rating: 4.4,
    numReviews: 96,
    reviews: [],
  },
  {
    name: 'Velvet Mule',
    price: 13500,
    description: 'A plush velvet mule on a 5 cm block heel with a pointed toe. Gold-tone hardware detail at the vamp. Evening-ready yet comfortable enough for a long dinner.',
    image: IMAGES.heels2,
    category: 'Footwear',
    gender: 'Women',
    season: 'Winter',
    stock: 18,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Burgundy', 'Forest', 'Black'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 54,
    reviews: [],
  },
  {
    name: 'Neoprene Sock Boot',
    price: 17500,
    description: 'A fashion-forward sock boot in stretch neoprene with a sculpted 8 cm heel. Pull-on fit with a pointed toe and a barely-there ankle coverage that elongates the leg.',
    image: IMAGES.boots1,
    category: 'Footwear',
    gender: 'Women',
    season: 'Winter',
    stock: 14,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Camel'],
    brand: 'Atelier X',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 43,
    reviews: [],
  },
  {
    name: 'Classic White Leather High-Top',
    price: 11000,
    description: 'A clean, unadorned high-top sneaker in full-grain leather. Padded collar, flat cotton laces, and a cupsole silhouette rooted in 1970s basketball heritage.',
    image: IMAGES.sneaker2,
    category: 'Footwear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 45,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black'],
    brand: 'Urban Luxe',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: true,
    discountPercent: 15,
    rating: 4.5,
    numReviews: 132,
    reviews: [],
  },

  // ══════════════════════════════════════════════════════
  // ACCESSORIES (13)
  // ══════════════════════════════════════════════════════
  {
    name: 'Structured Leather Top-Handle Bag',
    price: 68000,
    description: 'A structured top-handle bag in grained calfskin leather. Detachable shoulder strap, suede interior, and polished brass hardware. A timeless investment piece.',
    image: IMAGES.bag1,
    category: 'Accessories',
    gender: 'Women',
    season: 'All-Season',
    stock: 12,
    trending: true,
    sizes: ['M'],
    colors: ['Black', 'Tan', 'Burgundy'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 67,
    reviews: [],
  },
  {
    name: 'Quilted Chain-Strap Shoulder Bag',
    price: 52000,
    description: 'Diamond-quilted lambskin shoulder bag with a gold chain-link strap. Turn-lock closure, one interior zip pocket, and an iconic silhouette.',
    image: IMAGES.bag2,
    category: 'Accessories',
    gender: 'Women',
    season: 'All-Season',
    stock: 10,
    trending: true,
    sizes: ['S'],
    colors: ['Black', 'Beige', 'Navy'],
    brand: 'Atelier X',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 48,
    reviews: [],
  },
  {
    name: 'Canvas Tote with Leather Handles',
    price: 8500,
    description: 'Heavy-duty 16 oz canvas tote with saddle-leather top handles and a leather base. Interior zip pocket and a magnetic snap closure. The sophisticated everyday carry.',
    image: IMAGES.bag3,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 55,
    trending: false,
    sizes: ['L'],
    colors: ['Ecru', 'Navy', 'Black'],
    brand: 'Minimalist',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic', 'Vegan'],
    isSale: true,
    discountPercent: 10,
    rating: 4.6,
    numReviews: 155,
    reviews: [],
  },
  {
    name: 'Cashmere Blend Scarf',
    price: 12000,
    description: 'A generous 200 x 70 cm scarf in a cashmere-wool blend. Fringed ends and a subtle herringbone weave — endlessly drape-able through all cold months.',
    image: IMAGES.scarf1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Winter',
    stock: 40,
    trending: false,
    sizes: ['M'],
    colors: ['Camel', 'Grey', 'Navy', 'Burgundy'],
    brand: 'Heritage',
    material: 'Cashmere',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 98,
    reviews: [],
  },
  {
    name: 'Woven Leather Belt',
    price: 8500,
    description: 'Hand-woven Italian leather belt with a palladium-finished pin buckle. Available in multiple widths. A refined alternative to a plain strap.',
    image: IMAGES.belt1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 45,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Tan'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 87,
    reviews: [],
  },
  {
    name: 'Automatic Mechanical Watch',
    price: 95000,
    description: 'A Swiss-movement automatic watch with a 40 mm stainless-steel case, sapphire crystal, and an Italian leather strap. 80-hour power reserve. A lifetime companion.',
    image: IMAGES.watch1,
    category: 'Accessories',
    gender: 'Men',
    season: 'All-Season',
    stock: 8,
    trending: true,
    sizes: ['M'],
    colors: ['Black', 'Navy', 'Silver'],
    brand: 'Atelier X',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 33,
    reviews: [],
  },
  {
    name: 'Vintage-Frame Oval Sunglasses',
    price: 9500,
    description: 'Acetate oval-frame sunglasses with polarized UV400 lenses. Inspired by 1970s eyewear with a modern proportion. Comes with a hard case.',
    image: IMAGES.sunglasses1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Summer',
    stock: 50,
    trending: true,
    sizes: ['M'],
    colors: ['Tortoise', 'Black', 'Honey'],
    brand: 'Urban Luxe',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 119,
    reviews: [],
  },
  {
    name: 'Wide-Brim Sun Hat',
    price: 6800,
    description: 'A hand-woven natural straw wide-brim hat with a grosgrain ribbon. Adjustable inner drawstring. UPF 50+. The ultimate summer accessory.',
    image: IMAGES.hat1,
    category: 'Accessories',
    gender: 'Women',
    season: 'Summer',
    stock: 35,
    trending: true,
    sizes: ['M'],
    colors: ['Natural', 'Black-Ribbon'],
    brand: 'Fashion Hub',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Hand-crafted', 'Vegan'],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 74,
    reviews: [],
  },
  {
    name: 'Mini Leather Crossbody Bag',
    price: 22000,
    description: 'A compact crossbody in pebbled calfskin leather. Zip-top closure, one exterior pocket, and a 110 cm adjustable strap. Goes everywhere with everything.',
    image: IMAGES.bag3,
    category: 'Accessories',
    gender: 'Women',
    season: 'All-Season',
    stock: 28,
    trending: false,
    sizes: ['S'],
    colors: ['Black', 'Tan', 'Blush'],
    brand: 'Minimalist',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: true,
    discountPercent: 15,
    rating: 4.7,
    numReviews: 102,
    reviews: [],
  },
  {
    name: 'Silk Square Scarf',
    price: 15000,
    description: 'A 90 x 90 cm silk twill square scarf with a hand-rolled hem. Original botanical print designed in-house. Wears as a neck scarf, head wrap, or bag accent.',
    image: IMAGES.scarf1,
    category: 'Accessories',
    gender: 'Women',
    season: 'All-Season',
    stock: 22,
    trending: true,
    sizes: ['M'],
    colors: ['Floral-Print', 'Abstract-Print'],
    brand: 'Heritage',
    material: 'Silk',
    fit: 'Regular Fit',
    occasion: 'Formal',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 59,
    reviews: [],
  },
  {
    name: 'Slim Cardholder Wallet',
    price: 7500,
    description: 'A wafer-thin cardholder in RFID-shielded full-grain leather. Holds up to 6 cards with a centre slot for folded notes. The minimalist wallet done right.',
    image: IMAGES.belt1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 60,
    trending: false,
    sizes: ['S'],
    colors: ['Black', 'Brown', 'Tan', 'Navy'],
    brand: 'Minimalist',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 214,
    reviews: [],
  },
  {
    name: 'Knit Beanie — Unisex',
    price: 4500,
    description: 'A dense-ribbed beanie in a merino-cashmere blend. Rolled cuff and a subtle fold. The cold-weather essential that pairs with everything from ski jackets to overcoats.',
    image: IMAGES.hat1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Winter',
    stock: 75,
    trending: false,
    sizes: ['M'],
    colors: ['Black', 'Grey', 'Camel', 'Navy'],
    brand: 'Heritage',
    material: 'Cashmere',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: true,
    discountPercent: 10,
    rating: 4.7,
    numReviews: 186,
    reviews: [],
  },
  {
    name: 'Structured Weekend Duffle Bag',
    price: 45000,
    description: 'A full-grain leather weekend duffle with a structured base and brass hardware. Central zip compartment, two end pockets, and a removable shoulder strap. Built for a lifetime of travel.',
    image: IMAGES.bag2,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 10,
    trending: true,
    sizes: ['L'],
    colors: ['Brown', 'Black'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.9,
    numReviews: 47,
    reviews: [],
  },
  // ══════════════════════════════════════════════════════
  // BONUS MIX — 10 more to reach 100
  // ══════════════════════════════════════════════════════
  {
    name: 'Linen Co-ord Shirt & Short Set — Men',
    price: 9800,
    description: 'A relaxed matching set in stone-washed linen: a camp-collar shirt and mid-thigh shorts with an elasticated waist. The effortless summer travel set.',
    image: IMAGES.menCasual3,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'Summer',
    stock: 42,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Ecru', 'Sage', 'Sky-Blue'],
    brand: 'Minimalist',
    material: 'Linen',
    fit: 'Relaxed Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 83,
    reviews: [],
  },
  {
    name: 'Silk Pyjama Set — Unisex',
    price: 22000,
    description: 'A two-piece pyjama set in 19mm mulberry silk. Piped contrast trim, breast pocket, and wide-leg trousers with a self-tie waist. Luxury lounging done right.',
    image: IMAGES.womenCasual3,
    category: 'Ready-to-Wear',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 20,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Black', 'Sage'],
    brand: 'Atelier X',
    material: 'Silk',
    fit: 'Relaxed Fit',
    occasion: 'Lounge',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.8,
    numReviews: 64,
    reviews: [],
  },
  {
    name: 'Heritage Tattersall Flannel Shirt',
    price: 7500,
    description: 'A classic tattersall check flannel shirt in a brushed cotton-wool blend. Button-down collar, box pleat back, and a semi-tailored fit that works tucked or untucked.',
    image: IMAGES.menCasual2,
    category: 'Ready-to-Wear',
    gender: 'Men',
    season: 'Winter',
    stock: 55,
    trending: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red-Check', 'Blue-Check', 'Green-Check'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: true,
    discountPercent: 10,
    rating: 4.5,
    numReviews: 109,
    reviews: [],
  },
  {
    name: 'Asymmetric Hem Wrap Skirt',
    price: 8200,
    description: 'A fluid asymmetric hem skirt in a ponte-roma blend. Wrapped front, invisible zip, and a mid-thigh-to-knee asymmetric hem that adds dynamic movement.',
    image: IMAGES.womenSkirt,
    category: 'Ready-to-Wear',
    gender: 'Women',
    season: 'All-Season',
    stock: 33,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Burgundy', 'Olive'],
    brand: 'Fashion Hub',
    material: 'Technical',
    fit: 'Regular Fit',
    occasion: 'Work',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.5,
    numReviews: 71,
    reviews: [],
  },
  {
    name: 'Brushed Mohair Beret',
    price: 5500,
    description: 'A French-inspired beret in brushed kid-mohair. Slightly slouched crown, knitted edge band, and an adjustable inner ribbon. An elegant hat for all occasions.',
    image: IMAGES.hat1,
    category: 'Accessories',
    gender: 'Women',
    season: 'Winter',
    stock: 30,
    trending: true,
    sizes: ['M'],
    colors: ['Camel', 'Black', 'Burgundy', 'Grey'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 62,
    reviews: [],
  },
  {
    name: 'Trail Running Vest — Unisex',
    price: 7800,
    description: 'A lightweight trail running vest in recycled ripstop. Two front zip pockets and a back mesh compartment for fuel. Reflective piping for visibility.',
    image: IMAGES.athleisure1,
    category: 'Athleisure',
    gender: 'Unisex',
    season: 'All-Season',
    stock: 38,
    trending: false,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Orange', 'Navy'],
    brand: 'Zenith',
    material: 'Technical',
    fit: 'Slim Fit',
    occasion: 'Active',
    sustainability: ['Recycled'],
    isSale: false,
    discountPercent: 0,
    rating: 4.4,
    numReviews: 77,
    reviews: [],
  },
  {
    name: 'Suede Platform Chelsea Boot — Women',
    price: 28000,
    description: 'A fashion-forward update to the Chelsea silhouette: a premium suede upper, elastic gussets, and a chunky platform lug sole that adds 4 cm of height.',
    image: IMAGES.boots1,
    category: 'Footwear',
    gender: 'Women',
    season: 'All-Season',
    stock: 22,
    trending: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Tan', 'Burgundy'],
    brand: 'Urban Luxe',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: [],
    isSale: false,
    discountPercent: 0,
    rating: 4.7,
    numReviews: 88,
    reviews: [],
  },
  {
    name: 'Wool-Felt Fedora',
    price: 9500,
    description: 'A classic teardrop-crown fedora in 100% wool felt. Grosgrain ribbon band and a snapped front brim. Handblocked for shape retention.',
    image: IMAGES.hat1,
    category: 'Accessories',
    gender: 'Men',
    season: 'Winter',
    stock: 25,
    trending: false,
    sizes: ['M', 'L'],
    colors: ['Charcoal', 'Camel', 'Black'],
    brand: 'Heritage',
    material: 'Wool',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Hand-crafted'],
    isSale: true,
    discountPercent: 15,
    rating: 4.5,
    numReviews: 57,
    reviews: [],
  },
  {
    name: 'Double-Knit Jersey Track Suit',
    price: 16500,
    description: 'A twin-set track suit in premium double-knit jersey. Zip-up jacket with rib trims and matching tapered trousers with side stripes. Elevated sportswear heritage.',
    image: IMAGES.athleisure3,
    category: 'Athleisure',
    gender: 'Men',
    season: 'All-Season',
    stock: 30,
    trending: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Burgundy'],
    brand: 'Urban Luxe',
    material: 'Cotton',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Organic'],
    isSale: false,
    discountPercent: 0,
    rating: 4.6,
    numReviews: 92,
    reviews: [],
  },
  {
    name: 'Leather Gloves — Unisex',
    price: 11500,
    description: 'Touchscreen-compatible leather gloves with a cashmere lining. Stitched index finger detailing and a button-snap closure at the wrist. Warmth without compromise.',
    image: IMAGES.scarf1,
    category: 'Accessories',
    gender: 'Unisex',
    season: 'Winter',
    stock: 40,
    trending: false,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Brown', 'Navy'],
    brand: 'Heritage',
    material: 'Leather',
    fit: 'Regular Fit',
    occasion: 'Casual',
    sustainability: ['Ethically Sourced'],
    isSale: true,
    discountPercent: 10,
    rating: 4.7,
    numReviews: 104,
    reviews: [],
  },
];

// ─── DB Seeder ────────────────────────────────────────────────────────────────
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/fashionstore';

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');

    const inserted = await Product.insertMany(products);
    console.log(`🌱 Successfully inserted ${inserted.length} products`);

    await mongoose.disconnect();
    console.log('🔌 Disconnected');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
};

seed();

module.exports = { products }; // also importable without running seed